name: partner_app
description: "OmiBay Partner - Meet your experts"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^6.2.0
  provider: ^6.1.1
  http: ^1.2.2
  intl: ^0.20.0
  cached_network_image: ^3.4.0
  # carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.1.0
  #  pinput: ^7.3.0

  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  google_places_flutter: ^2.1.1

  image_picker: ^1.1.1
  permission_handler: ^12.0.0
  #  razorpay_flutter: ^2.1.0
  shared_preferences: ^2.4.1

  # Firebase removed for static operation
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_messaging: ^16.1.0

  uuid: ^4.4.0
  equatable: ^2.0.5
  get_it: ^7.6.4
  dio: ^5.4.3
  flutter_bloc: ^8.1.4

  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  flutter_svg: ^2.0.9
  flutter_material_design_icons: ^1.1.7447
  palette_generator: ^0.3.2
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  razorpay_flutter: ^1.4.0
  fluttertoast: ^8.2.14
  pinput: ^6.0.1
  carousel_slider: ^5.1.1
  audioplayers: ^5.2.1
  share_plus: ^12.0.1
  video_player: ^2.8.1
  video_compress: ^3.1.4
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
#  fluttertoast: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - audio/
    - icons/